# Generated by Django 5.2.7 on 2026-04-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_reporte_llamar_911_reporte_nivel_urgencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/fotos/', verbose_name='Foto de evidencia (opcional)'),
        ),
    ]
